
name: offline_first_case_mgmt
description: Offline-first Flutter app (Windows + Android) using Supabase + Drift + Riverpod with lookups cache and sync engine.
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
